---
# tasks file for ansible-chrony
- name: Gather system facts
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_facts['os_family'] | lower }}.yml"
      paths:
        - "{{ role_path }}/vars"

- name: Install Chrony
  package:
    name: chrony
    state: present
    update_cache: yes
    cache_valid_time: "{{ '3600' if ansible_facts.pkg_mgr == 'apt' else omit }}"
  become: true

- import_tasks: config_chrony.yml
